server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.52.128:3306/idempotent_pay?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.52.128
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl